version: '3'

services:
  frontend: 
   build: 
     context: ./frontend
     dockerfile: Dockerfile.prod
   container_name: realwordl-docker-frontend
   command: serve -s build -l 3000
   restart: unless-stopped

  api:
   build: ./api
   container_name: realworld-docker-api
   #start
   command: npm run start
   #restart docker compose
   restart: unless-stopped
   #left host different port - right container
   environment:
     - PORT=3001
     - MONGO_URL=mongodb://api_db:27017/api
     - AUTH_API=http://auth:3002
     - MAILER_API=http://mailer:3003
   depends_on:
     - api_db
  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  mailer:
    build: ./mailer
    container_name: realworld-docker-mailer
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3003
    depends_on:
     - api
     - auth  

  api_db:
    image: mongo:latest
    container_name: realworld-docker-api-db
    volumes:
      - mongodb_api:/data/db
  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db
  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
  
volumes:
    mongodb_api:
    mongodb_auth:
